version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting build phase..."

  build:
    commands:
      - echo "Copying files for build..."
      - rsync -av --exclude=terraform_files --exclude=buildspec.yml ./ artifact/

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - 'terraform_files/**/*'
    - 'buildspec.yml'
  base-directory: 'artifact'
  discard-paths: yes
